### PR TITLE
updated WindowSpy for AHK v2

### PR DESCRIPTION
**Pull request by TheArkive**
Update Window Spy for AHK v2
... Should be ready now.

### CODE REVIEW

**Comment by Lexikos** [comment]
Why did you delete WindowSpy.v1.ahk? I'm guessing that was unintentional.

**Comment by TheArkive** [comment]
My bad.  I thought this was a separate repo for v2.  I'll put it back.

**Comment by Lexikos** [comment]
All of the release scripts still run on v1, and of course, I use the same scripts to release different versions of AutoHotkey. I put "v1" in the name of the file because I intended for there eventually to be both versions present at once. Actually, the whole installer\source folder will probably need to be duplicated since v2 will have its own installer written in v2. (I'll probably continue using the v1 installer for v1 releases, but include some code to make it play nice with any previously installed v2/multi-version installer.)

**Comment by Lexikos** [comment]
I would prefer not to include the removal and restoration of the v1 file in the commit history. Also, your last commit seems to not have any purpose, as it only removes a newline character which was present at the end of the original file. I would use `git rebase -i` to squash/fix the commit that introduced the error, and `git push -f` (which might need additional parameters) to update the PR; although I suppose you might not be using command line git.

However, it seems that `git blame` and `git gui blame` are unaffected, so this is probably pedantic.

**Comment by TheArkive** [comment]
Ok, I'll work on removing those.  I use Git for windows, not the Github editor, so I can do the command line stuff.

**Comment by TheArkive** [comment]
Did that work?  it seems to have removed erroneous commits.

**Comment by TheArkive** [comment]
Let me know if this works.  I tried on the command line but I didn't actually see a list of commits (error message stated there was no tracking information).  When I ran the rebase command again specifying the branch, it didn't seem to list anything except the rebase that was about to happen.  Sorry, and am a bit of a noob on git stuff.

EDIT: I can replicate what I did and go back further (I think).

**Comment by SafetyCar** [comment]
I was looking around, it seems like there was an error updating the line 124. Previously taking _curCtrl_ but then changed to _curWin_.

**Comment by TheArkive** [comment]
Good catch, thanks.

**Comment by safetycar** [comment]
Eh, sorry that I deleted the comment I was not sure about it and started to doubt about if it was a problem.
I thought it was easier to pretend I didn't say anything, but you saw the comment before that.
So it's fine by me if you want to join that last change with the previous.

**Comment by TheArkive** [comment]
Heh actually, the returned dimensions were wrong for W/H, so it worked out.

EDIT: The H/W was permanently set to the window client width given how I queried the values.

**Comment by Lexikos** [comment]
Looks fine, although I might leave this open until I've worked out what I need to change to integrate the separate v2 installer into the release process.

Amusingly, the email I received about the force push just said:
> @TheArkive pushed 0 commits.

**Comment by TheArkive** [comment]
I'm fine with that.  I don't want to mess with it too much more.  As long as it is to your liking for the project.

**Comment by TheArkive** [comment]
I figure some minor updates were in order to address the change for `CoordMode` default from "Window" to "Client".  A few other things jumped out at me that seemed worth changing.  Let me know if you want me to change/refine/revert any of these updates.

**Pull request merged**
