### PR TITLE
WindowSpy.v2.ahk for AHK v2

### PR DESCRIPTION
**Pull request by steelywing**
Issue #6

### CODE REVIEW

**Comment by Lexikos** [comment]
I prefer a more direct translation of the v1 code, but adapted to the newer, recommended methods of error handling.

>     ; Ignore error, sometimes update() will issue window not found error
>     ; Comment this out when debug
>     OnError((*) => true)

This is not a technique that I would recommend, so is not something I will include in an "official" script. Rather than ignoring all errors and proceeding as though the window exists, the script should handle cases where the target window does not exist (or is closed during the update). This could be done a number of ways, the simplest probably being to enclose the call to update() in try-catch TargetError.

>     loop parse controls `n

This contains three errors:
  1. There's no comma between the two parameters.
  2. There's no quote marks around the newline sequence.
  3. WinGetControlsHwnd has returned an Array, not a string, since v2.0-a104.

>     WinGetPos(wX, wY,,, "ahk_id " hWnd)
>     if (IsInteger(wX)) {
>         x += wX
>     }
>     if (IsInteger(wY)) {
>         y += wY
>     }

Ideally all "official" scripts should should be suitable examples for those learning to use AutoHotkey v2. This is not. It is not immediately obvious that these checks are only necessary because you've changed the overall behaviour of the script with OnError. WinGetPos should always return integers, so checking the type of output is strange. There's also no guarantee that the values will be non-numeric if an error occurs. It should be sufficient to do something like:

    try
        WinGetPos &wX, &wY,,, hWnd
    catch TargetError
        return false
    x += wX, y += wY

For a122, you would omit the `&` and `TargetError`. Note that `"ahk_id "` is useful only if you want DetectHiddenWindows to be applied.

> GetClientSize

I suppose this is superseded by WinGetClientPos.

**Comment by Lexikos** [comment]
Actually, most of what I said about OnError isn't actually applicable to your script. I responded to your comment "Ignore error", but now realize you're returning `true`, not `-1`. The latter would cause the error to be ignored and allow the thread to continue execution after whatever Win/Control function, while the former just suppresses the error messages. The error is not *ignored*, as such; it still causes the thread to exit.

Still, this method of error "handling" is not ideal, and not good for an "official" script.

I've probably also forgotten that the Win functions didn't throw in whatever version you wrote the script for. Maybe in that version the IsInteger checks were necessary.

**Comment by steelywing** [comment]
Thanks for the review, I don't know AHK v2 will change that much when writing this script, sorry forget to mention the working AHK version, the script should works with [**AHK a122**](https://www.autohotkey.com/boards/viewtopic.php?t=72333) version.

I will update this script for the newest AHK v2 later.

**Comment by steelywing** [comment]
@Lexikos I have update the compatible and issue to my [master branch](https://github.com/steelywing/AutoHotkey-Release/blob/master/installer/source/WindowSpy.v2.ahk), check if you are interest

**Pull request closed without merging**
